# Generated by Django 5.2.10 on 2026-03-19 20:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissaomensalsalao',
            name='meta_faturamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
