# Generated by Django 5.2.10 on 2026-03-20 14:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models
from django.db.models import F


def seed_formas_pagamento_and_backfill(apps, schema_editor):
    FormaPagamentoSalao = apps.get_model('salao', 'FormaPagamentoSalao')
    TaxaFormaPagamentoSalao = apps.get_model('salao', 'TaxaFormaPagamentoSalao')
    LancamentoSalao = apps.get_model('salao', 'LancamentoSalao')

    formas_defaults = [
        ('0', 'Não informado', False),
        ('1', 'PIX', False),
        ('2', 'Crédito', True),
        ('3', 'Dinheiro', False),
        ('4', 'Débito', False),
    ]

    formas_by_code = {}
    for codigo, nome, aceita_parcelamento in formas_defaults:
        forma, _ = FormaPagamentoSalao.objects.get_or_create(
            codigo=codigo,
            defaults={
                'nome': nome,
                'ativo': True,
                'aceita_parcelamento': aceita_parcelamento,
            },
        )
        formas_by_code[codigo] = forma

    for codigo in ('0', '1', '3', '4'):
        forma = formas_by_code.get(codigo)
        if forma:
            TaxaFormaPagamentoSalao.objects.get_or_create(
                forma_pagamento=forma,
                parcelas=1,
                defaults={'percentual': Decimal('0.00')},
            )

    forma_nao_informado = formas_by_code.get('0')
    if forma_nao_informado:
        LancamentoSalao.objects.filter(forma_pagamento__isnull=True).update(
            forma_pagamento=forma_nao_informado,
            parcelas=1,
            valor_bruto=F('valor_cobrado'),
            taxa_percentual_aplicada=Decimal('0.00'),
            valor_taxa=Decimal('0.00'),
        )


def seed_formas_pagamento_and_backfill_reverse(apps, schema_editor):
    # Sem rollback destrutivo de dados de negócio.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0002_comissaomensalsalao_meta_faturamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamentoSalao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('ativo', models.BooleanField(default=True)),
                ('aceita_parcelamento', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Forma de Pagamento do Salão',
                'verbose_name_plural': 'Formas de Pagamento do Salão',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterModelOptions(
            name='categoriadespesasalao',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria de Despesa do Salão', 'verbose_name_plural': 'Categorias de Despesa do Salão'},
        ),
        migrations.AlterModelOptions(
            name='servicosalao',
            options={'ordering': ['codigo'], 'verbose_name': 'Serviço do Salão', 'verbose_name_plural': 'Serviços do Salão'},
        ),
        migrations.RemoveField(
            model_name='categoriadespesasalao',
            name='ordem',
        ),
        migrations.RemoveField(
            model_name='servicosalao',
            name='ordem',
        ),
        migrations.AddField(
            model_name='despesasalao',
            name='grupo_parcelamento_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='despesasalao',
            name='parcela_numero',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='despesasalao',
            name='parcelas_total',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='lancamentosalao',
            name='parcelas',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='lancamentosalao',
            name='taxa_percentual_aplicada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='lancamentosalao',
            name='valor_bruto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='lancamentosalao',
            name='valor_taxa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='lancamentosalao',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='salao.formapagamentosalao'),
        ),
        migrations.CreateModel(
            name='TaxaFormaPagamentoSalao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcelas', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxas', to='salao.formapagamentosalao')),
            ],
            options={
                'verbose_name': 'Taxa da Forma de Pagamento do Salão',
                'verbose_name_plural': 'Taxas da Forma de Pagamento do Salão',
                'ordering': ['forma_pagamento__codigo', 'parcelas'],
                'constraints': [models.UniqueConstraint(fields=('forma_pagamento', 'parcelas'), name='unique_taxa_forma_pagamento_parcelas_salao')],
            },
        ),
        migrations.RunPython(
            seed_formas_pagamento_and_backfill,
            seed_formas_pagamento_and_backfill_reverse,
        ),
    ]
