# Generated by Django 5.2.10 on 2026-03-26 20:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0003_formapagamentosalao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoSalao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=140)),
                ('unidade', models.CharField(default='UN', max_length=20)),
                ('valor_venda_padrao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('saldo_atual', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('custo_medio_atual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto do Salão',
                'verbose_name_plural': 'Produtos do Salão',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='despesasalao',
            name='gera_estoque',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CompraEstoqueSalao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('parcelas_total', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('grupo_parcelamento_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_estoque', to='salao.categoriadespesasalao')),
            ],
            options={
                'verbose_name': 'Compra de Estoque do Salão',
                'verbose_name_plural': 'Compras de Estoque do Salão',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.AddField(
            model_name='despesasalao',
            name='compra_estoque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_financeiras', to='salao.compraestoquesalao'),
        ),
        migrations.CreateModel(
            name='MovimentoEstoqueSalao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('motivo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda'), ('USO_EM_CLIENTE', 'Uso em Cliente'), ('AJUSTE', 'Ajuste')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('custo_unitario_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_custo_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_venda_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_bruto_venda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('taxa_percentual_aplicada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('valor_taxa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_liquido_venda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('lucro_produto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('parcelas', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('compra_estoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_entrada', to='salao.compraestoquesalao')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_estoque', to='salao.formapagamentosalao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='salao.produtosalao')),
            ],
            options={
                'verbose_name': 'Movimento de Estoque do Salão',
                'verbose_name_plural': 'Movimentos de Estoque do Salão',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CompraEstoqueItemSalao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='salao.compraestoquesalao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_compra', to='salao.produtosalao')),
            ],
            options={
                'verbose_name': 'Item de Compra de Estoque do Salão',
                'verbose_name_plural': 'Itens de Compra de Estoque do Salão',
                'ordering': ['compra_id', 'id'],
            },
        ),
    ]
