# Generated by Django 5.2.10 on 2026-04-02 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0004_produtosalao_despesasalao_gera_estoque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoriaDespesaSalao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='salao.categoriadespesasalao')),
            ],
            options={
                'verbose_name': 'Subcategoria de Despesa do Salão',
                'verbose_name_plural': 'Subcategorias de Despesa do Salão',
                'ordering': ['categoria__nome', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='despesasalao',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='salao.subcategoriadespesasalao'),
        ),
        migrations.AddConstraint(
            model_name='subcategoriadespesasalao',
            constraint=models.UniqueConstraint(fields=('categoria', 'nome'), name='unique_subcategoria_por_categoria_salao'),
        ),
    ]
