# Generated by Django 5.2.10 on 2026-05-14 12:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0005_subcategoriadespesasalao_despesasalao_subcategoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraestoquesalao',
            name='custos_adicionais',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
