# Generated by Django 5.2.10 on 2026-07-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0007_lancamentosalao_permuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentosalao',
            name='sem_comissao',
            field=models.BooleanField(default=False),
        ),
    ]
