# Generated by Django 5.2.10 on 2026-09-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0009_lancamentosalao_conferido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoIgnoradaSalao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=120, unique=True)),
                ('referencia', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transação Ignorada do Salão',
                'verbose_name_plural': 'Transações Ignoradas do Salão',
                'ordering': ['-criado_em'],
            },
        ),
    ]
