# Generated by Django 5.2.10 on 2026-09-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0010_transacaoignoradasalao'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoestoquesalao',
            name='conferido',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='movimentoestoquesalao',
            name='conferido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
