# Generated by Django 5.2.10 on 2026-09-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0011_movimentoestoquesalao_conferido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentosalao',
            name='taxa_repassada',
            field=models.BooleanField(default=False),
        ),
    ]
