# Generated by Django 5.2.10 on 2026-09-02 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0012_lancamentosalao_taxa_repassada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacaoManualSalao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.UUIDField(db_index=True)),
                ('identificador', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lancamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conciliacao_manual', to='salao.lancamentosalao')),
                ('movimento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conciliacao_manual', to='salao.movimentoestoquesalao')),
            ],
            options={
                'verbose_name': 'Conciliação Manual do Salão',
                'verbose_name_plural': 'Conciliações Manuais do Salão',
                'ordering': ['grupo', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('identificador__isnull', False), ('lancamento__isnull', True), ('movimento__isnull', True)), models.Q(('identificador__isnull', True), ('lancamento__isnull', False), ('movimento__isnull', True)), models.Q(('identificador__isnull', True), ('lancamento__isnull', True), ('movimento__isnull', False)), _connector='OR'), name='conciliacao_manual_uma_ponta_por_linha')],
            },
        ),
    ]
