# Generated by Django 5.2.10 on 2026-09-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0013_conciliacaomanualsalao'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagamentosalao',
            name='concilia_extrato',
            field=models.BooleanField(default=True),
        ),
    ]
