# Generated by Django 5.2.10 on 2026-09-03 19:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0015_dinheiro_fora_do_extrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoDivididaSalao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_origem', models.CharField(db_index=True, max_length=140)),
                ('identificador', models.CharField(max_length=140, unique=True)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descricao', models.CharField(blank=True, max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Divisão de Transação do Salão',
                'verbose_name_plural': 'Divisões de Transação do Salão',
                'ordering': ['identificador_origem', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='conciliacaomanualsalao',
            name='identificador',
            field=models.CharField(blank=True, max_length=140, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transacaoignoradasalao',
            name='identificador',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
