# Generated by Django 5.2.10 on 2026-01-28 20:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.IntegerField(help_text='Mês (1-12)')),
                ('ano_referencia', models.IntegerField(help_text='Ano (ex: 2025)')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('vencimento', models.DateField()),
                ('order_nsu', models.CharField(blank=True, help_text='NSU do pedido InfinitePay', max_length=100)),
                ('invoice_slug', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('transaction_nsu', models.CharField(blank=True, help_text='NSU da transação', max_length=100)),
                ('capture_method', models.CharField(blank=True, max_length=50)),
                ('receipt_url', models.URLField(blank=True, help_text='URL do recibo de pagamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-ano_referencia', '-mes_referencia'],
                'indexes': [models.Index(fields=['mes_referencia', 'ano_referencia'], name='invoices_in_mes_ref_3c8198_idx'), models.Index(fields=['status'], name='invoices_in_status_cec546_idx'), models.Index(fields=['vencimento'], name='invoices_in_vencime_c20665_idx')],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'mes_referencia', 'ano_referencia'), name='unique_invoice_per_cliente_month')],
            },
        ),
    ]
