# Generated by Django 5.2.10 on 2026-01-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-ano_referencia', '-mes_referencia', '-criado_em'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_invoice_per_cliente_month',
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['cliente', 'mes_referencia', 'ano_referencia'], name='invoices_in_cliente_284768_idx'),
        ),
    ]
