# Generated by Django 5.2.10 on 2026-02-03 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoicecontrato_unique_invoice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoicecontrato',
            new_name='invoices_in_invoice_a115f4_idx',
            old_name='invoices_in_invoice__f9d171_idx',
        ),
        migrations.RenameIndex(
            model_name='invoicecontrato',
            new_name='invoices_in_contrat_e1055a_idx',
            old_name='invoices_in_contrato_1495d0_idx',
        ),
    ]
