# Generated by Django 5.2.10 on 2026-02-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_invoice_checkout_url_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagequeue',
            name='tipo',
            field=models.CharField(choices=[('5_dias', '5 dias antes'), ('2_dias', '2 dias antes'), ('no_dia', 'No dia'), ('atraso', 'Atraso'), ('confirmacao', 'Confirmação')], max_length=20),
        ),
    ]
