# Generated by Django 5.2.10 on 2026-02-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_invoice_checkout_url_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='descricao',
            field=models.CharField(blank=True, help_text='Descrição específica desta cobrança (ex: "Desenvolvimento de feature X"). Quando preenchida, substitui a descrição padrão do cliente nas mensagens e no checkout. Deixe em branco para usar a descrição padrão do cliente.', max_length=255),
        ),
        migrations.AlterField(
            model_name='messagequeue',
            name='tipo',
            field=models.CharField(choices=[('5_dias', '5 dias antes'), ('2_dias', '2 dias antes'), ('no_dia', 'No dia'), ('atraso', 'Atraso'), ('confirmacao', 'Confirmação')], max_length=20),
        ),
    ]
