# Generated by Django 5.2.10 on 2026-02-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_messagequeue_tipo'),
        ('invoices', '0008_descricao_cobranca'),
    ]

    operations = [
    ]
