# Generated by Django 5.2.10 on 2026-01-28 20:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPSBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('fornecedor', models.CharField(blank=True, max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('vps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='vps.vps')),
            ],
        ),
        migrations.CreateModel(
            name='VPSBackupCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodo_meses', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('vencimento', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costs', to='backups.vpsbackup')),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
    ]
