# Generated by Django 5.2.10 on 2026-02-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_vencimento_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='descricao_cobranca',
            field=models.CharField(blank=True, help_text='Descrição padrão exibida nas mensagens e no checkout de cobrança deste cliente. Quando em branco, usa o padrão do sistema.', max_length=255),
        ),
    ]
