# Generated by Django 5.2.10 on 2026-01-29 19:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='valor_mensal',
            field=models.DecimalField(decimal_places=2, help_text='Valor mensal do contrato. Pode ser 0 para contratos internos.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
