# Generated by Django 5.2.10 on 2026-01-28 20:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dominios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(help_text='Ex: Hostinger, Google, Zoho', max_length=200)),
                ('quantidade_caixas', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='dominios.dominio')),
            ],
        ),
        migrations.CreateModel(
            name='DomainEmailCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodo_meses', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('vencimento', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costs', to='emails.domainemail')),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
    ]
