# Generated by Django 5.2.10 on 2026-01-28 20:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('ano', models.PositiveSmallIntegerField()),
                ('fechado', models.BooleanField(default=False)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('fechado_por', models.CharField(blank=True, max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ano', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('mes', 'ano'), name='unique_periodo_financeiro')],
            },
        ),
        migrations.CreateModel(
            name='ContratoSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receita', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_dominios', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('custo_hostings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('custo_vps', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('custo_backups', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('custo_emails', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margem_percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('detalhamento', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='contratos.contrato')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrato_snapshots', to='financeiro.periodofinanceiro')),
            ],
            options={
                'ordering': ['-periodo__ano', '-periodo__mes'],
                'constraints': [models.UniqueConstraint(fields=('contrato', 'periodo'), name='unique_contrato_snapshot')],
            },
        ),
    ]
