# Generated by Django 5.2.10 on 2026-01-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratosnapshot',
            name='margem_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Margem percentual. NULL para contratos internos (sem receita)', max_digits=8, null=True),
        ),
    ]
