# Generated by Django 5.2.10 on 2026-01-29 21:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_alter_contrato_valor_mensal'),
        ('financeiro', '0002_alter_contratosnapshot_margem_percentual'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratosnapshot',
            name='custo_despesas_adicionais',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Despesas adicionais/excepcionais do período', max_digits=10),
        ),
        migrations.AlterField(
            model_name='contratosnapshot',
            name='receita',
            field=models.DecimalField(decimal_places=2, help_text='Receita REAL do período (soma de invoices pagos)', max_digits=10),
        ),
        migrations.CreateModel(
            name='DespesaAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text="Descrição da despesa (ex: 'Licença Office 365', 'Suporte emergencial')", max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da despesa', max_digits=10)),
                ('mes_referencia', models.PositiveSmallIntegerField(help_text='Mês em que a despesa deve ser contabilizada (1-12)')),
                ('ano_referencia', models.PositiveSmallIntegerField(help_text='Ano da despesa (ex: 2025)')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.CharField(blank=True, max_length=200)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas_adicionais', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Despesa Adicional',
                'verbose_name_plural': 'Despesas Adicionais',
                'ordering': ['-ano_referencia', '-mes_referencia', '-criado_em'],
                'indexes': [models.Index(fields=['mes_referencia', 'ano_referencia'], name='financeiro__mes_ref_cfd666_idx'), models.Index(fields=['contrato'], name='financeiro__contrat_cd5b7b_idx')],
            },
        ),
    ]
